import type { Feature } from "@/types";
import {
  FEATURE_CATEGORIES,
  AI_PROVIDERS,
  ARTICLE_PROMPTS,
  NOVEL_PROMPTS,
  NEWS_PROMPTS,
  EDUCATIONAL_PROMPTS,
  TECHNICAL_PROMPTS,
} from "@/utils/constants";

const COMMON_EMPTY_PROMPTS = {
  novel: "",
  news: "",
  article: "",
  educational: "",
  code: "",
  general: "",
};

export const defaultFeatures: Feature[] = [
  {
    id: "enhance",
    name: "Enhance Text",
    description: "Improve readability and flow of the content",
    icon: "✨",
    category: FEATURE_CATEGORIES.ENHANCE,
    supportedModes: ["novel", "article", "general"],
    isRecent: false,
    defaultPrompts: {
      novel: NOVEL_PROMPTS.enhance,
      article: ARTICLE_PROMPTS.enhance,
      news: NEWS_PROMPTS.enhance,
      educational: EDUCATIONAL_PROMPTS.enhance,
      code: TECHNICAL_PROMPTS.enhance,
      general: "Please enhance the readability and flow of this content.",
    },
    defaultSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
    config: {
      serviceId: AI_PROVIDERS.GEMINI,
      modelId: "gemini-2.0-flash",
      customPrompts: { ...COMMON_EMPTY_PROMPTS },
      customSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
      enabled: true,
    },
  },
  {
    id: "summarize",
    name: "Summarize",
    description: "Create a concise summary of the content",
    icon: "📝",
    category: FEATURE_CATEGORIES.ANALYZE,
    supportedModes: ["novel", "article", "news", "educational", "general"],
    isRecent: false,
    defaultPrompts: {
      novel: NOVEL_PROMPTS.summarize,
      article: ARTICLE_PROMPTS.summarize,
      news: NEWS_PROMPTS.summarize,
      educational: EDUCATIONAL_PROMPTS.summarize,
      code: TECHNICAL_PROMPTS.summarize,
      general:
        "Please provide a concise summary of this content, highlighting the main points.",
    },
    defaultSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
    config: {
      serviceId: AI_PROVIDERS.GEMINI,
      modelId: "gemini-2.0-flash",
      customPrompts: { ...COMMON_EMPTY_PROMPTS },
      customSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
      enabled: true,
    },
  },
  {
    id: "analyze",
    name: "Analyze",
    description: "Provide detailed explanations of complex concepts",
    icon: "💡",
    category: FEATURE_CATEGORIES.ANALYZE,
    supportedModes: ["educational", "code", "article", "general"],
    isRecent: false,
    defaultPrompts: {
      novel: NOVEL_PROMPTS.analyze,
      article: ARTICLE_PROMPTS.analyze,
      news: NEWS_PROMPTS.analyze,
      educational: EDUCATIONAL_PROMPTS.analyze,
      code: TECHNICAL_PROMPTS.analyze,
      general:
        "Please provide a detailed explanation of the concepts presented in this content.",
    },
    defaultSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
    config: {
      serviceId: AI_PROVIDERS.GEMINI,
      modelId: "gemini-2.0-flash",
      customPrompts: { ...COMMON_EMPTY_PROMPTS },
      customSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
      enabled: true,
    },
  },
  {
    id: "suggestions",
    name: "Suggestions",
    description: "Translate content to different languages",
    icon: "🌐",
    category: FEATURE_CATEGORIES.TRANSFORM,
    supportedModes: ["novel", "article", "news", "educational", "general"],
    isRecent: false,
    defaultPrompts: {
      novel: NOVEL_PROMPTS.suggestions,
      article: ARTICLE_PROMPTS.suggestions,
      news: NEWS_PROMPTS.suggestions,
      educational: EDUCATIONAL_PROMPTS.suggestions,
      code: TECHNICAL_PROMPTS.suggestions,
      general: "Please translate this content to [TARGET_LANGUAGE].",
    },
    defaultSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
    config: {
      serviceId: AI_PROVIDERS.GEMINI,
      modelId: "gemini-2.0-flash",
      customPrompts: { ...COMMON_EMPTY_PROMPTS },
      customSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
      enabled: true,
    },
  },
  {
    id: "questions",
    name: "Generate Questions",
    description: "Create study questions or discussion points",
    icon: "❓",
    category: FEATURE_CATEGORIES.UTILITY,
    supportedModes: ["educational", "article", "novel"],
    isRecent: false,
    defaultPrompts: {
      novel:
        "Please generate thoughtful discussion questions about this novel text, focusing on themes, characters, and plot development.",
      article:
        "Please generate study questions based on this article to help with comprehension and critical thinking.",
      news: "Please generate discussion questions about this news story to encourage critical analysis.",
      educational:
        "Please generate study questions and practice problems based on this educational content.",
      code: "Please generate questions that would help someone understand and learn from this code.",
      general: "Please generate thoughtful questions based on this content.",
    },
    defaultSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
    config: {
      serviceId: AI_PROVIDERS.GEMINI,
      modelId: "gemini-2.0-flash",
      customPrompts: { ...COMMON_EMPTY_PROMPTS },
      customSystemPrompts: { ...COMMON_EMPTY_PROMPTS },
      enabled: true,
    },
  },
];
